# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'TuneinLife' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  
  
  
  
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'Bolts'
  pod 'FBSDKLoginKit', '~>4.0'
  pod 'FBSDKCoreKit',  '~>4.0'
  pod 'FBSDKShareKit', '~>4.0'
 
 
 
 
 
 
 
 
 
 
  # Pods for TuneinLife
  target 'TuneinLifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TuneinLifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
